
# Files generated by Windows build

WIN_CLEANUP = config.nice.bat Release_TS configure.bat configure.js

PHPC_EMBED = $(srcdir)/php/src/internal/tools/embed.php

.PHONY: phpc parser_code tools_code

phpc: parser_code tools_code

parser_code:
	$(PHP_EXECUTABLE) $(PHPC_EMBED) $(srcdir)/php/src/internal/parser \
		parser_code $(srcdir)/php/phpc/$@.phpc

tools_code:
	$(PHP_EXECUTABLE) $(PHPC_EMBED) $(srcdir)/php/src/internal/tools \
		tools_code $(srcdir)/php/phpc/$@.phpc

cleanup: clean
	phpize --clean
	@rm -rf $(WIN_CLEANUP) include modules

fulltest:
	sh travis/run-test.sh
