
# Files generated by Windows build

WIN_CLEANUP = config.nice.bat Release_TS configure.bat configure.js

PHPC_EMBED = pcs://internal/tools/embed.php
PHPC_CMD = $(PHP_EXECUTABLE) -d "extension=pcs.$(SHLIB_DL_SUFFIX_NAME)" -r "require '$(PHPC_EMBED)';" --

.PHONY: phpc code1 code2 code3 empty

#-----------------------

phpc: code1 code2 code3 empty

code1:
	$(PHPC_CMD) $(srcdir)/php/src/$@ $@ $(srcdir)/php/phpc/$@.phpc

code2:
	$(PHPC_CMD) $(srcdir)/php/src/$@ $@ $(srcdir)/php/phpc/$@.phpc

code3:
	$(PHPC_CMD) $(srcdir)/php/src/$@ $@ $(srcdir)/php/phpc/$@.phpc

empty:
	[ -d $(srcdir)/php/src/$@ ] || mkdir $(srcdir)/php/src/$@
	$(PHPC_CMD) $(srcdir)/php/src/$@ $@ $(srcdir)/php/phpc/$@.phpc

#-----------------------

cleanup: clean
	phpize --clean
	@rm -rf $(WIN_CLEANUP) include modules
