/* This file was generated by the pcs_process_code.php utility. */
/*-------------------- DO NOT MODIFY --------------------*/

static char code2_string0[]= { /* ext/ptest/Dummy1.php */
  60, 63, 112, 104, 112, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
  10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 110, 97, 109, 101, 115, 
  112, 97, 99, 101, 32, 80, 67, 83, 95, 84, 101, 115, 116, 32, 123, 10, 
  10, 99, 108, 97, 115, 115, 32, 68, 117, 109, 109, 121, 49, 10, 123, 10, 
  10, 125, 32, 10, 10, 125, 32, 10, 10, 0 };


static struct {
	int version;
	char *data;
	PCS_SIZE_T data_len;
	char *path;
	PCS_SIZE_T path_len;
} code2[2] = {
  { 0, code2_string0, 73, "ext/ptest/Dummy1.php", 20 },
  { 0, NULL }
};
