/* This file was generated by the pcs_process_code.php utility. */
/*-------------------- DO NOT MODIFY --------------------*/


static struct {
	int version;
	char *data;
	PCS_SIZE_T data_len;
	char *path;
	PCS_SIZE_T path_len;
} empty[1] = {
  { 0, NULL }
};
