/* This file was generated by the pcs_process_code.php utility. */
/*-------------------- DO NOT MODIFY --------------------*/


static struct {
	int version;
	char *data;
	size_t data_len;
	char *path;
	size_t path_len;
} empty[1] = {
  { 0, NULL }
};
